python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 1e-4 --num_layer 3  --width 512 
python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 5e-4 --num_layer 3  --width 512 
python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 1e-3 --num_layer 3  --width 512 
python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 5e-3 --num_layer 3  --width 512 
python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 1e-2 --num_layer 3  --width 512 
python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 5e-2 --num_layer 3  --width 512 
python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 1e-1 --num_layer 3  --width 512 
python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 5e-1 --num_layer 3  --width 512 
python nn_exp.py --inv_op_power 1 --folder new_plot --noise_level 1 --num_layer 3  --width 512 