SYSTEM:
  TEST_FREQ: -1
WANDB:
  PROJECT_NAME: 'ANON'
  MODE: 'online'
DATA:
  DATASET: 'BinaryCIFAR10'
  DATA_N: 40000
  TRAIN_N: 40000
  BATCH_SIZE: 128
  FLATTEN_INPUT: True
  LABEL_NOISE: 0.0
  EVAL_NOISY_TEST: True
  ONE_HOT_ENCODE: True
  RANDOMIZE_LABELS: False
  NORM_SCALE:
    mean: (0.4914, 0.4822, 0.4465)
    std: (0.2023, 0.1994, 0.201)
MODEL:
  MODEL_TYPE: 'feedforward'
  INP_DIM: 3072
  N_HID_LAYERS: 3
  HID_DIM: 3072
  OUT_DIM: 2
  DROPOUT_RATE: 0.0
OPT:
  OPT_ALG: 'adam'
  LEARNING_RATE: 1e-3
  GRAD_CLIP: None
  MOMENTUM: 0.9
  NESTEROV: False
  LR_SCHEDULE: 'multi_step_lr' #'multi_step_lr'
  LR_MILESTONES: [30, 40] #[80, 120, 160] #[30, 40] #[80, 120, 160]
  LR_GAMMA: 0.1
  TRAIN_LOSS_EPSILON_STOP: 1e-4
  WEIGHT_DECAY: 0.0
  WARMUP_LR: False
  WARMUP_EPOCHS: 10
  TOTAL_EPOCHS: 50
